#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set up docker
eval "$(docker-machine env default)"

export KEYTIMEOUT=1
bindkey -M vicmd '/' vi-history-search-backward

export EDITOR=vim
export VISUAL=vim
